name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      – master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Client/Dockerfile
          push: true
          tags: user/repo:latest

      - name: Run Docker Compose
        run: docker-compose up -d
